/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xznn_myffmpegdemo_MainActivity */

#ifndef _Included_ffmpeg_demo
#define _Included_ffmpeg_demo

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xznn_myffmpegdemo_MainActivity
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xznn_myffmpegdemo_MainActivity_urlprotocolinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_xznn_myffmpegdemo_MainActivity
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xznn_myffmpegdemo_MainActivity_avformatinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_xznn_myffmpegdemo_MainActivity
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xznn_myffmpegdemo_MainActivity_avcodecinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_xznn_myffmpegdemo_MainActivity
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xznn_myffmpegdemo_MainActivity_avfilterinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_xznn_myffmpegdemo_MainActivity
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xznn_myffmpegdemo_MainActivity_configurationinfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
